// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgcee2jipVimVIe2rTXKeCfkCcbmDYCxo',
    appId: '1:127012570370:web:29103a55cdc8a847ae2e1b',
    messagingSenderId: '127012570370',
    projectId: 'cathub-19cda',
    authDomain: 'cathub-19cda.firebaseapp.com',
    storageBucket: 'cathub-19cda.appspot.com',
    measurementId: 'G-J2JY5V44TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHvvSPqX2v_TnE3SrLrv1oF6Z43CsCxs',
    appId: '1:127012570370:android:432208ff8e476d18ae2e1b',
    messagingSenderId: '127012570370',
    projectId: 'cathub-19cda',
    storageBucket: 'cathub-19cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuP9g3QhAZf_IoPoqKLznEsfT9-FEM_DI',
    appId: '1:127012570370:ios:7febd1e90a8a140fae2e1b',
    messagingSenderId: '127012570370',
    projectId: 'cathub-19cda',
    storageBucket: 'cathub-19cda.appspot.com',
    iosClientId: '127012570370-cmle0loqfps7ioi78i91ngta7jhcqdra.apps.googleusercontent.com',
    iosBundleId: 'com.example.bottomNav',
  );
}
